
name: Compensation-Management-Platform

services:
  gateway:
    build:
      context: .
      dockerfile: Gateway.Dockerfile
    container_name: gateway
    image: gateway:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${GATEWAY_PORT}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - EVENT_SERVICE_URL=${EVENT_SERVICE_URL}
    networks:
      - reward-network
    depends_on:
      - mongodb
    restart: unless-stopped


  auth-service:
    build:
      context: .
      dockerfile: Auth.Dockerfile
    container_name: auth-service
    image: auth-service:latest
    ports:
      - "3010:3010"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${AUTH_PORT}
    networks:
      - reward-network
    depends_on:
      - mongodb
    restart: unless-stopped

  event-service:
    build:
      context: .
      dockerfile: Event.Dockerfile
    container_name: event-service
    image: event-service:latest
    ports:
      - "3020:3020"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${EVENT_PORT}
    networks:
      - reward-network
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nexon
      - MONGO_INITDB_ROOT_PASSWORD=maple
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    networks:
      - reward-network
    restart: always


networks:
  reward-network:
    driver: bridge

volumes:
  mongodb_data:
