### GET request to example server
GET http://localhost:3010

### GET request to example server
GET http://localhost:3020

###
GET http://localhost:3010/user


###
POST http://localhost:3010/user/signUp
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test1234!",
  "role": "user"
}


###
POST http://localhost:3010/user/signIn
Content-Type: application/json

{
  "username": "testuser",
  "password": "Test1234!"
}