### 회원가입
POST http://localhost:3000/api/auth/user/signUp
Content-Type: application/json

{
  "username": "user",
  "password": "Test1234!"
}



### 로그인
POST http://localhost:3000/api/auth/user/signIn
Content-Type: application/json

{
  "username": "user",
  "password": "Test1234!"
}

> {% client.global.set("access_token", response.body.access_token); %}

### 보상 요청
POST http://localhost:3000/api/event/request/:event_id
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "event_id" : "0196e395-7939-71f3-b801-f7665bf4cdb2"
}


### 보상 요청 조회
GET http://localhost:3000/api/event/request
Content-Type: application/json
Authorization: Bearer {{access_token}}